sync: synchronization.cpp
#	    g++ -march=skylake-avx512 -O3 -std=c++17 -g -Wall synchronization.cpp -o sync -ltbb
	    g++ -march=native -O3 -std=c++17 -g -Wall synchronization.cpp -o sync -ltbb -pthread